Feature Selection: Filtros

Correlação

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

raw_data = pd.read_csv('wisconsin.csv')

raw_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,1.184,2.776,3.001,1.471,...,25.38,17.33,184.60,2019.0,1.622,6.656,7.119,2.654,4.601,1.189
1,842517,M,20.57,17.77,132.90,1326.0,8.474,7.864,869.000,7.017,...,24.99,23.41,158.80,1956.0,1.238,1.866,2.416,186.000,275.000,8.902
2,84300903,M,19.69,21.25,130.00,1203.0,1.096,1.599,1.974,1.279,...,23.57,25.53,152.50,1709.0,1.444,4.245,4.504,243.000,3.613,8.758
3,84348301,M,11.42,20.38,77.58,386.1,1.425,2.839,2.414,1.052,...,14.91,26.50,98.87,567.7,2.098,8.663,6.869,2.575,6.638,173.000
4,84358402,M,20.29,14.34,135.10,1297.0,1.003,1.328,198.000,1.043,...,22.54,16.67,152.20,1575.0,1.374,205.000,0.400,1.625,2.364,7.678

In [ ]:
data = raw_data.drop(['id'], axis=1)
data.head()

input = data.drop(['diagnosis'], axis=1)
output = data['diagnosis']


corr = input.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
input

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,1184.0,2776.0,3001.0,1471,2419.0,7871.0,...,25.38,17.33,184.60,2019.0,1622.0,6656.0,7119.0,2654.0,4601.0,1189.0
1,20.57,17.77,132.90,1326.0,8474.0,7864.0,869.0,7017,1812.0,5667.0,...,24.99,23.41,158.80,1956.0,1238.0,1866.0,2416.0,186.0,275.0,8902.0
2,19.69,21.25,130.00,1203.0,1096.0,1599.0,1974.0,1279,2069.0,5999.0,...,23.57,25.53,152.50,1709.0,1444.0,4245.0,4504.0,243.0,3613.0,8758.0
3,11.42,20.38,77.58,386.1,1425.0,2839.0,2414.0,1052,2597.0,9744.0,...,14.91,2025-05-26 00:00:00,98.87,567.7,2098.0,8663.0,6869.0,2575.0,6638.0,173.0
4,20.29,14.34,135.10,1297.0,1003.0,1328.0,198.0,1043,1809.0,5883.0,...,22.54,16.67,152.20,1575.0,1374.0,205.0,0.4,1625.0,2364.0,7678.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.0,1159.0,2439.0,1389,1726.0,5623.0,...,25.45,2025-04-26 00:00:00,166.10,2027.0,141.0,2113.0,4107.0,2216.0,206.0,7115.0
565,20.13,28.25,131.20,1261.0,978.0,1034.0,144.0,9791,1752.0,5533.0,...,23.69,38.25,155.00,1731.0,1166.0,1922.0,3215.0,1628.0,2572.0,6637.0
566,2025-06-16 00:00:00,2025-08-28 00:00:00,108.30,858.1,8455.0,1023.0,9251.0,5302,159.0,5648.0,...,18.98,34.12,126.70,1124.0,1139.0,3094.0,3403.0,1418.0,2218.0,782.0
567,2025-06-20 00:00:00,29.33,140.10,1265.0,1178.0,277.0,3514.0,152,2397.0,7016.0,...,25.74,39.42,184.60,1821.0,165.0,8681.0,9387.0,265.0,4087.0,124.0
568,7.76,24.54,47.92,181.0,5263.0,4362.0,0.0,0,1587.0,5884.0,...,9456,30.37,59.16,268.6,8996.0,6444.0,0.0,0.0,2871.0,7039.0

In [ ]:
limiar = 0.9
selecionados = set() # evitar elementos duplicados usando set() ['perimeter_worst','perimeter_worst']

for i in range(len(corr.columns)):
    for j in range(i):
        if abs(corr.iloc[i,j]) > limiar:
            coluna_i = corr.columns[i]
            coluna_j = corr.columns[j]
            selecionados.add(coluna_i)


print(selecionados)
print(len(selecionados))
print(len(corr.columns))


input_selected = input.drop(list(selecionados), axis=1)
input_selected.head()

{'perimeter_mean', 'texture_worst', 'area_worst', 'perimeter_worst', 'area_mean', 'radius_worst'}
6
30

,radius_mean,texture_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,...,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,1.184,2.776,3.001,1.471,2.419,7.871,1.095,9.053,...,5.373,1.587,3.003,6.193,1.622,6.656,7.119,2.654,4.601,1.189
1,20.57,17.77,8.474,7.864,869.000,7.017,1.812,5.667,5.435,7.339,...,186.000,134.000,1.389,3.532,1.238,1.866,2.416,186.000,275.000,8.902
2,19.69,21.25,1.096,1.599,1.974,1.279,2.069,5.999,7.456,7.869,...,3.832,2.058,225.000,4.571,1.444,4.245,4.504,243.000,3.613,8.758
3,11.42,20.38,1.425,2.839,2.414,1.052,2.597,9.744,4.956,1.156,...,5.661,1.867,5.963,9.208,2.098,8.663,6.869,2.575,6.638,173.000
4,20.29,14.34,1.003,1.328,198.000,1.043,1.809,5.883,7.572,7.813,...,5.688,1.885,1.756,5.115,1.374,205.000,0.400,1.625,2.364,7.678

Processo de classificação usando Naive Bayes

In [ ]:
#NaiveBayes
from sklearn import naive_bayes as NB
from sklearn.model_selection import train_test_split

#Usando toda a base de dados
results_full = []
results_selected = []
for ex in range(30):

  input_train, input_test, output_train, output_test = train_test_split(input, output, test_size=0.2,random_state=ex)

  my_nb_full = NB.GaussianNB()
  my_nb_full.fit(input_train, output_train)

  results_full.append(my_nb_full.score(input_test, output_test))



  # Usando a base selecionada

  input_train_selected, input_test_selected, output_train_selected, output_test_selected = train_test_split(input_selected, output, test_size=0.2,random_state=ex)
  my_nb_selected = NB.GaussianNB()
  my_nb_selected.fit(input_train_selected, output_train_selected)

  results_selected.append(my_nb_selected.score(input_test_selected, output_test_selected))

print(np.mean(results_full))
print(np.mean(results_selected))

print(np.std(results_full))
print(np.std(results_selected))

0.9377192982456142
0.9116959064327488
0.018026973850056558
0.01973630062068562

Wrappers

In [ ]:
from sklearn.datasets import load_iris
from sklearn import naive_bayes as NB
import pandas as pd
import warnings
warnings.simplefilter("ignore")


data = load_iris()
input = data.data
output = data.target



#selected = [[0,0,0,1],[0,0,1,0],[0,0,1,1],[0,1,0,0],[0,1,0,1],[0,1,1,0],[0,1,1,1],[1,0,0,0],[1,0,0,1],[1,0,1,0],[1,0,1,1],[1,1,0,0],[1,1,0,1],[1,1,1,0],[1,1,1,1]] #2**n - 1   [0,0,0,0]
selected = [[False,False,False,True],[False,False,True,False],[False,False,True,True],[False,True,False,False],[False,True,False,True],[False,True,True,False],[False,True,True,True],[True,False,False,False],[True,False,False,True],[True,False,True,False],[True,False,True,True],[True,True,False,False],[True,True,False,True],[True,True,True,False],[True,True,True,True]] #(2**n) - 1   [False,False,False,False]
#Meta-heurísticas - algoritmos genéticos, inteligência de enxames

# N, 2**N -1
# N = 30
my_df = pd.DataFrame(input)
output = pd.DataFrame(output)
score_limiar =0
best_model=0
best_selected=[]
input_train, input_test, output_train, output_test = train_test_split(my_df, output, test_size=0.2,random_state=3465)
for i in selected:
  input_train_selected = input_train.iloc[:,i]

  input_train_selected_div = input_train.iloc[:int(0.8*len(input_train_selected)),i]
  output_train_selected_div = output_train.iloc[:int(0.8*len(input_train_selected))]
  input_val_selected_div = input_train.iloc[int(0.8*len(input_train_selected)):,i]
  output_val_selected_div = output_train.iloc[int(0.8*len(input_train_selected)):]


  my_nb = NB.GaussianNB().fit(input_train_selected_div, output_train_selected_div)


  score_aux = my_nb.score(input_val_selected_div, output_val_selected_div)
  print(score_aux)
  if score_aux >= score_limiar:
    score_limiar = score_aux
    best_model = my_nb
    best_selected = i

print(best_selected)


print(best_model.score(input_test.iloc[:,best_selected], output_test))

0.9583333333333334
0.875
0.9166666666666666
0.5416666666666666
0.9583333333333334
0.875
0.9166666666666666
0.7916666666666666
0.9583333333333334
0.875
0.875
0.875
0.9166666666666666
0.875
0.9166666666666666
[True, False, False, True]
0.9666666666666667

In [ ]:
input_train.iloc[:,i]

       3
137  1.8
84   1.5
27   0.2
127  1.8
132  2.2
..   ...
9    0.1
103  1.8
67   1.0
117  2.2
47   0.2

[120 rows x 1 columns]